/**
 * One-off generator: turn the collected chess.com labels into a data file.
 *
 * Only ZERO-count games are emitted as labels here, and that restriction is the
 * point. chess.com's post-game summary is unlimited but over-counts relative to
 * full Game Review, so "0 brilliancies" is exact and complete while "1" only
 * tells you a star exists somewhere — not that it's on the move we flagged. A
 * pile of exact negatives is worth more than a pile of maybes, especially for a
 * detector whose problem is false positives.
 *
 *   node scripts/make-labels.mjs > scripts/labels-louismcdade.mjs
 */
import { writeFileSync } from "node:fs";

const USER = "louismcdade";

// gameId -> brilliancies chess.com reports for LouisMcdade's side.
// "review" = confirmed in full Game Review (authoritative about WHICH move).
// "summary" = post-game highlights (exact only when the count is 0).
const LABELS = {
  // — confirmed by full Game Review —
  "168334603690": { n: 1, src: "review", move: "6...Bxf2+" },
  "169999249810": { n: 1, src: "review", move: "24.Ne6" },
  // — summary, zero: exact and complete —
  "171473275764": { n: 0, src: "summary" },
  "169135347664": { n: 0, src: "summary" },
  "170905472716": { n: 0, src: "summary" },
  "171329245690": { n: 0, src: "summary" },
  "71922350989": { n: 0, src: "summary" },
  "59328109305": { n: 0, src: "summary" },
  "123030583107": { n: 0, src: "summary" },
  "69023093493": { n: 0, src: "summary" },
  "78155551321": { n: 0, src: "summary" },
  "75729696237": { n: 0, src: "summary" },
  "167769830480": { n: 0, src: "summary" },
  "69169474795": { n: 0, src: "summary" },
  "123984651203": { n: 0, src: "summary" },
  "75090176179": { n: 0, src: "summary" },
  // — summary, one: a star exists, but not necessarily on the move we flag —
  "172078598998": { n: 1, src: "summary", guess: "15...Nxd3+" },
  "170344245882": { n: 1, src: "summary", guess: "41.Qf6+" },
  "169869209718": { n: 1, src: "summary", note: "we flag TWO here — at least one is wrong" },
  "72012130191": { n: 1, src: "summary", guess: "23...Nd4+" },
  "166907239486": { n: 1, src: "summary", guess: "11.Nxd5" },
};


// A game is scoreable only when we know WHICH move chess.com starred: zero-count
// games (nothing is starred) and Game-Review-confirmed games. A summary count of
// 1 tells us a star exists but not where, so it stays null.
const expected = (lab) => {
  if (lab.n === 0) return "[]";
  if (lab.src === "review" && lab.move) {
    const m = lab.move.match(/^(\d+)\.+(.+)$/);
    return `[{ moveNumber: ${m[1]}, san: "${m[2]}" }]`;
  }
  return "null";
};

async function getJson(url) {
  const res = await fetch(url, { headers: { Accept: "application/json" } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

const months = (await getJson(`https://api.chess.com/pub/player/${USER}/games/archives`)).archives;
const found = new Map();

for (let i = months.length - 1; i >= 0 && found.size < Object.keys(LABELS).length; i--) {
  let games;
  try {
    ({ games } = await getJson(months[i]));
  } catch {
    continue;
  }
  for (const g of games ?? []) {
    const id = String(g.url).split("/").pop();
    if (!LABELS[id] || found.has(id)) continue;
    const userColor = (g.white?.username ?? "").toLowerCase() === USER ? "w" : "b";
    const moves = (g.pgn.split(/\n\n/)[1] ?? "")
      .replace(/\{[^}]*\}/g, "")
      .replace(/\d+\.\.\./g, "")
      .replace(/\s+/g, " ")
      .trim();
    found.set(id, {
      url: g.url,
      userColor,
      opp: userColor === "w" ? g.black?.username : g.white?.username,
      pgn: moves,
    });
  }
}

const missing = Object.keys(LABELS).filter((id) => !found.has(id));
if (missing.length) console.error("NOT FOUND in archives:", missing.join(", "));

const wrap = (s, indent = "      ") => {
  const out = [];
  let line = "";
  for (const tok of s.split(" ")) {
    if (line.length + tok.length > 78) {
      out.push(line.trimEnd());
      line = "";
    }
    line += tok + " ";
  }
  if (line.trim()) out.push(line.trimEnd());
  return out.map((l) => `${indent}"${l} "`).join(" +\n").replace(/ "$/, '"');
};

let out = `/**
 * chess.com's own labels for LouisMcdade's games — the ground truth this project
 * exists to approximate, and the only labels here that weren't written by us.
 *
 * Collected from chess.com Game Review and post-game summaries. The summary
 * over-counts relative to Game Review, so a count of 0 is exact and a count of 1
 * only means a star exists somewhere in the game. Games with a nonzero count are
 * therefore recorded but NOT turned into positive fixtures: claiming the star is
 * on the move we happened to flag would be assuming what we're trying to test.
 *
 * Generated by scripts/make-labels.mjs. Edit LABELS there, not this file.
 */
export const chesscomLabels = [
`;

for (const [id, lab] of Object.entries(LABELS)) {
  const g = found.get(id);
  if (!g) continue;
  const note =
    lab.n === 0
      ? "chess.com: zero brilliancies for this side. Exact — anything we flag here is a false positive."
      : `chess.com: ${lab.n} brilliancy (${lab.src}).${lab.move ? ` Confirmed move: ${lab.move}.` : lab.guess ? ` We flag ${lab.guess}; unconfirmed which move chess.com starred.` : ""}${lab.note ? ` ${lab.note}` : ""}`;
  out += `  {
    id: "${id}",
    url: "${g.url}",
    name: "vs ${g.opp} — ${lab.n === 0 ? "no brilliancy" : `${lab.n} brilliancy`} (chess.com)",
    userColor: "${g.userColor}",
    count: ${lab.n},
    source: "${lab.src}",
    // ${note}
    expected: ${expected(lab)},${lab.n > 0 && lab.src !== "review" ? " // unknown which move — not scoreable as a positive" : ""}
    pgn:
${wrap(g.pgn)},
  },
`;
}
out += "];\n";

writeFileSync("scripts/labels-louismcdade.mjs", out);
console.error(`wrote ${found.size} labelled games`);
